name: country_state_city_selector
description: A customizable Flutter widget for selecting country → state → city with adaptive Material & Cupertino UI.
version: 0.1.0
homepage: https://github.com/wisdomscode/country_state_city_selector
repository: https://github.com/wisdomscode/country_state_city_selector
issue_tracker: https://github.com/wisdomscode/country_state_city_selector/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  assets:
    - assets/countries.json
    - test/assets/countries.json